[package]
name = "patp"
version = "0.1.0"
authors = ["Joe Harrison <joeyh021@icloud.co,>"]
edition = "2018"
repository = "https://github.com/Joeyh021/PATP"

 
[dependencies]
thiserror = "1.0"
anyhow = "1.0"
clap = "2.33.3"
